"""Esqueleto del programa: qué bloques existen y de qué va cada uno.

Esto es la estructura pedagógica, que sí se puede fijar por adelantado. La prosa de cada
slide y —sobre todo— cada afirmación normativa de los cursos 3 y 4 se escriben después, con
la fuente primaria delante. Ver `content/tools/scaffold.py`.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Block:
    task: str
    course: str
    block_id: str
    title: str
    objective: str
    slides: list[str]
    lab: str | None
    takeaways: list[str]
    quiz_topics: list[str]

    # Fuentes primarias que hay que tener delante para escribir el bloque. Solo los bloques
    # normativos las llevan: es lo que impide redactar de memoria.
    sources: list[str] = field(default_factory=list)
    needs_verification: bool = False


COURSE_3 = "agentes-en-produccion"
COURSE_4 = "gobernanza-eu"

BLOCKS: list[Block] = [
    # ── C-01 · Extensión del curso 1 ────────────────────────────────────────────────────
    Block(
        task="C-01",
        course="prompt-engineering",
        block_id="PE-A",
        title="Prompts como código",
        objective=(
            "Tratar los prompts como artefactos de software: versionados, revisados en PR y "
            "con tests que fallan cuando se rompen."
        ),
        slides=[
            "Por qué un prompt en un string literal es deuda técnica",
            "El repositorio de prompts: estructura de carpetas y convenciones",
            "Versionado: qué cambia cuando cambia un prompt",
            "Variables tipadas: un prompt con huecos no es una plantilla de texto",
            "Interpolación segura: por qué concatenar entrada de usuario es una vulnerabilidad",
            "El prompt de extracción de FNOL de Meridiana, antes y después",
            "Tests de regresión de prompts: qué se afirma exactamente",
            "Casos dorados: cuántos, quién los elige y cuándo se actualizan",
            "Umbrales: cuándo un test de prompt falla y cuándo solo avisa",
            "Review de un prompt en PR: qué mira quien revisa",
            "Diff de prompts: por qué el diff de texto no basta",
            "Rollback: volver a la versión anterior sin volver a desplegar",
            "Entornos: el mismo prompt en desarrollo y en producción",
            "Anti-patrón: el prompt que se edita en producción desde un panel",
            "Anti-patrón: el prompt de 4.000 palabras que nadie se atreve a tocar",
            "Métricas por prompt: exactitud, formato, coste y latencia",
            "Qué NO va en el repositorio de prompts",
            "Plantillas parciales y composición: cuándo ayuda y cuándo enreda",
            "El system prompt frente al prompt de tarea: qué va en cada uno",
            "Prompts por idioma: el problema de mantener dos verdades",
            "Fixtures: de dónde salen los datos de los tests de prompt",
            "Ejecutar los tests de prompt sin llamar al modelo en cada PR",
            "Coste de los tests de prompt en CI y cómo acotarlo",
            "Propiedad del prompt: quién lo revisa cuando no es código de producto",
            "Documentar la intención de un prompt para quien lo herede",
            "Migrar un prompt entre versiones de modelo",
        ],
        lab="Convertir los prompts del agente Meridiana a un repositorio versionado con tests de regresión.",
        takeaways=[
            "Un prompt sin test es una función sin test, con peor tipado.",
            "El diff útil de un prompt es el de sus salidas, no el de su texto.",
            "Si un prompt no se puede revertir en un minuto, no está en producción: está suelto.",
        ],
        quiz_topics=[
            "Qué distingue un test de regresión de prompt de un test unitario normal",
            "Por qué interpolar el relato del asegurado directamente en el prompt es un riesgo",
            "Cuándo un cambio de prompt exige regenerar los casos dorados",
        ],
    ),
    Block(
        task="C-01",
        course="prompt-engineering",
        block_id="PE-B",
        title="Structured outputs y evals",
        objective=(
            "Conseguir salidas que el código pueda consumir sin parsear texto, y medir si el "
            "prompt funciona en vez de opinar."
        ),
        slides=[
            "El problema de pedirle JSON a un modelo y confiar",
            "JSON Schema como contrato entre el modelo y el código",
            "Tool calling como mecanismo de salida estructurada",
            "Campos ausentes: la diferencia entre null, cadena vacía y alucinación",
            "Validación en el borde: qué se rechaza y qué se reintenta",
            "Reintento con el error como contexto: el patrón y sus límites",
            "Diseñar el schema de extracción de FNOL de Meridiana",
            "Enums frente a texto libre: cuándo cerrar el vocabulario",
            "Qué es un eval y en qué se diferencia de un test",
            "Eval de exactitud: comparar contra etiquetas que alguien decidió",
            "Eval de formato: el porcentaje de salidas que validan a la primera",
            "Eval de coste: tokens por caso y su traducción a euros",
            "Construir el conjunto de evaluación: los 31 siniestros de Meridiana",
            "Casos difíciles a propósito: por qué el dataset incluye una inyección",
            "Prompt caching: qué se cachea y qué no",
            "El impacto del caching en la factura, con números",
            "Cuándo el caching cambia el diseño del prompt",
            "Interpretar un eval que empeora: modelo, prompt o dataset",
            "Salidas parciales: qué hacer con un JSON truncado",
            "Límites de tokens de salida y su efecto sobre el schema",
            "Schemas anidados: hasta dónde llega la fiabilidad",
            "Campos opcionales frente a campos obligatorios en el contrato",
            "Versionar el schema junto al prompt",
            "Eval de latencia: percentiles, no medias",
            "Comparar dos prompts con significación: cuántos casos hacen falta",
            "Del eval al informe: qué se le enseña a negocio",
            "Cuándo dejar de optimizar el prompt y cambiar el diseño",
        ],
        lab="Añadir salida estructurada y un conjunto de evals al extractor de FNOL, con informe de coste.",
        takeaways=[
            "Un campo que falta se devuelve ausente; rellenarlo con lo probable es inventar.",
            "Sin conjunto de evaluación no hay forma de saber si un cambio de prompt mejora algo.",
            "El coste de un prompt es una propiedad medible, no una sorpresa de fin de mes.",
        ],
        quiz_topics=[
            "Qué hacer cuando el modelo devuelve JSON válido pero semánticamente imposible",
            "Por qué un eval con 5 casos no dice nada",
            "Qué parte del prompt conviene poner primero si se va a cachear",
        ],
    ),

    # ── C-02 → C-08 · Curso 3 · Agentes en Producción ──────────────────────────────────
    Block(
        task="C-02",
        course=COURSE_3,
        block_id="B1",
        title="De demo a sistema: arquitectura de referencia",
        objective=(
            "Reestructurar un agente que funciona en un portátil en un sistema con capas, "
            "límites de confianza y una idea clara de dónde vive el modelo y dónde no."
        ),
        slides=[
            "Qué separa una demo de un sistema: la lista honesta",
            "Las cuatro capas: gateway, orquestador, tools y memoria",
            "El gateway: autenticación, cuotas y forma de la petición",
            "El orquestador: dónde vive el loop y por qué no en el controlador HTTP",
            "Tools como frontera de confianza, no como funciones auxiliares",
            "Memoria: qué se guarda, cuánto dura y quién puede leerlo",
            "Deterministic-first: la regla y su coste",
            "Qué decisiones NO delega Meridiana en el modelo, y por qué",
            "Poner las reglas en código y no en el prompt: el argumento completo",
            "Límites de confianza: el relato del asegurado es dato, nunca instrucción",
            "El modelo como dependencia sustituible: el puerto ILlmClient",
            "Idempotencia: qué pasa si el mismo siniestro entra dos veces",
            "Estado: por qué el loop no debe guardar nada en memoria de proceso",
            "Colas y trabajos largos: cuándo un agente deja de ser síncrono",
            "Reintentos: qué se puede reintentar sin duplicar efectos",
            "Timeouts en cada salto, incluido el modelo",
            "Degradación: qué hace el sistema cuando el proveedor está caído",
            "Multi-tenant y aislamiento, si aplica",
            "Reestructurar Meridiana: el antes y el después en un diagrama",
            "Qué NO hay que abstraer todavía",
            "El contrato de una tool: nombre, schema y cuándo usarla",
            "Cuántas tools son demasiadas y qué pasa entonces",
            "Contexto: qué se arrastra entre iteraciones y qué se recalcula",
            "Ventana de contexto como recurso finito, no como límite lejano",
            "Cuándo un agente debe convertirse en varios",
            "El coste de coordinar dos agentes frente a uno más grande",
            "Versionado del contrato entre gateway y orquestador",
            "Pruebas de arquitectura: qué se comprueba automáticamente",
        ],
        lab="Reestructurar el repositorio meridiana-agent según la arquitectura de referencia, sin cambiar su comportamiento.",
        takeaways=[
            "El modelo propone; el código dispone. Toda regla con consecuencias vive en código.",
            "Una tool es una frontera de confianza, y se diseña como tal.",
            "Si el sistema no funciona con el proveedor caído, no está en producción.",
        ],
        quiz_topics=[
            "Dónde debe vivir la regla de derivar por lesiones y por qué",
            "Qué se puede reintentar sin efectos duplicados en el flujo de Meridiana",
            "Qué distingue una tool bien diseñada de una envoltura de la base de datos",
        ],
    ),
    Block(
        task="C-03",
        course=COURSE_3,
        block_id="B2",
        title="Observabilidad de sistemas con LLM",
        objective=(
            "Poder responder «por qué hizo eso» sobre una ejecución concreta de hace tres "
            "semanas, sin adivinar."
        ),
        slides=[
            "La pregunta que hay que poder responder: por qué hizo eso",
            "Por qué los logs de siempre no bastan aquí",
            "Trazas: el vocabulario mínimo (span, atributo, contexto)",
            "Instrumentar el loop: un span por iteración",
            "Instrumentar las tools: entrada, salida y error",
            "Qué se guarda del prompt y qué no",
            "Datos personales en las trazas: el problema y sus salidas",
            "Redacción y seudonimización antes de exportar",
            "Métricas que importan: latencia, tokens, coste, tasa de derivación",
            "La métrica que casi nadie pone: iteraciones por resolución",
            "Muestreo: por qué guardar el 100 % es caro y el 1 % es inútil",
            "Muestreo dirigido: guardar siempre los casos que fallan",
            "Correlación: del ticket del cliente a la traza en dos saltos",
            "Alertas que se pueden atender frente a alertas que se silencian",
            "Dashboards: los cuatro paneles que se miran de verdad",
            "Reconstruir un caso: el recorrido completo sobre un siniestro de Meridiana",
            "Retención: cuánto tiempo y por qué ese tiempo",
            "OpenTelemetry sin acoplarse al backend",
            "Coste de la observabilidad y cómo se controla",
            "Logs estructurados: qué sigue teniendo sentido loguear",
            "Identificadores que atraviesan el sistema entero",
            "Versión de prompt y de modelo como atributos de la traza",
            "Reproducir una ejecución a partir de su traza",
            "Grabar y reproducir: trazas como fixtures de test",
            "Paneles para negocio frente a paneles para guardia",
            "Qué mide bien el porcentaje de derivaciones y qué esconde",
            "Errores del proveedor: distinguir caído, limitado y lento",
            "El primer día con observabilidad: qué sorprende siempre",
        ],
        lab="Instrumentar Meridiana con OpenTelemetry y reconstruir, desde la traza, por qué se derivó un siniestro concreto.",
        takeaways=[
            "Si no puedes reconstruir una decisión de hace un mes, no tienes observabilidad.",
            "Guardar el prompt entero con datos personales dentro es crear un problema nuevo.",
            "El muestreo dirigido conserva lo que importa: los fallos.",
        ],
        quiz_topics=[
            "Qué atributos debe llevar el span de una tool para ser útil en una investigación",
            "Por qué el muestreo aleatorio puro es mala idea en un agente",
            "Qué hacer con los datos personales que aparecen en el relato antes de exportarlo",
        ],
    ),
    Block(
        task="C-04",
        course=COURSE_3,
        block_id="B3",
        title="Evals continuas",
        objective=(
            "Pasar de «probé unos cuantos casos y parecía bien» a una comprobación que corre "
            "en cada cambio y bloquea el despliegue cuando debe."
        ),
        slides=[
            "Por qué los evals de un cuaderno no sobreviven al primer mes",
            "Conjunto de evaluación: cómo se construye y quién lo mantiene",
            "Etiquetas: quién decide la respuesta correcta y con qué criterio",
            "El dataset de Meridiana: 31 casos y por qué esos",
            "Casos difíciles a propósito: lesiones, inyección, datos ausentes, duplicado",
            "Evals deterministas: exactitud, formato, cobertura de reglas",
            "Evals con modelo como juez: cuándo sirven y cuándo engañan",
            "El sesgo del juez: por qué no se usa el mismo modelo que genera",
            "Métricas por caso frente a métricas agregadas",
            "El agregado que oculta: 95 % de acierto con el 100 % de lesiones mal",
            "Segmentar: por vía, por canal, por dificultad",
            "Evals en CI: qué se ejecuta en cada PR y qué de noche",
            "Coste y tiempo de un eval en CI, y cómo acotarlos",
            "Umbrales de bloqueo: qué impide desplegar",
            "Regresiones: detectar que un cambio empeora algo que iba bien",
            "Deriva: cuándo el problema es el modelo y no el código",
            "Actualizar el conjunto sin invalidar el histórico",
            "Evals en producción: muestreo y revisión humana",
            "El bucle completo: producción alimenta el conjunto de evaluación",
            "Anotación humana: cuánta hace falta y quién la hace",
            "Desacuerdo entre anotadores: qué significa y qué hacer",
            "Evals de seguridad como conjunto aparte",
            "Evals de coste y latencia junto a los de calidad",
            "Comparar dos modelos con el mismo conjunto",
            "Fugas de datos entre el conjunto de evaluación y el desarrollo",
            "Versionar el conjunto de evaluación y su historia",
            "El eval que nadie mira: síntomas y cura",
        ],
        lab="Montar los evals de Meridiana en CI con umbrales que bloquean el merge, incluida la regla de lesiones.",
        takeaways=[
            "Un eval que nunca bloquea nada es documentación, no una comprobación.",
            "El agregado puede ir bien mientras el segmento que importa va mal: segmenta siempre.",
            "El conjunto de evaluación se alimenta de producción o envejece.",
        ],
        quiz_topics=[
            "Cuándo un modelo como juez es apropiado y cuándo no",
            "Qué umbral tiene sentido para la regla de derivar por lesiones",
            "Cómo detectar una regresión que el agregado no muestra",
        ],
    ),
    Block(
        task="C-05",
        course=COURSE_3,
        block_id="B4",
        title="Costes y rendimiento",
        objective=(
            "Saber lo que cuesta el sistema por caso y por mes, y qué pasa el día que "
            "llegan seiscientos siniestros en veinticuatro horas."
        ),
        slides=[
            "El coste por caso: cómo se calcula de verdad",
            "Tokens de entrada y de salida: la asimetría de precio",
            "El coste escondido: los reintentos",
            "El coste escondido: el contexto que se arrastra entre iteraciones",
            "Prompt caching: mecánica y ahorro real",
            "Diseñar el prompt para que el caching sirva",
            "Elegir modelo por tarea: cuándo el pequeño basta",
            "Cascada de modelos: barato primero, caro si hace falta",
            "El coste de la cascada cuando el barato falla mucho",
            "Batching: qué se puede agrupar en Meridiana y qué no",
            "Latencia percibida frente a latencia real",
            "Streaming: cuándo mejora la experiencia y cuándo solo la complica",
            "Paralelizar tools independientes",
            "Presupuesto por caso: cortar antes de gastar de más",
            "Presupuesto por tenant y por día",
            "El pico de granizo: 600 siniestros en 24 horas",
            "Colas, contrapresión y degradación ordenada",
            "Límites de tasa del proveedor y qué hacer con ellos",
            "Modelar el coste mensual con números de Meridiana",
            "Alertas de coste que avisan antes de la factura, no después",
            "Atribuir coste por cliente, por vía y por versión de prompt",
            "El coste de los evals en CI y cuándo empieza a doler",
            "Contexto largo frente a recuperación: el cálculo honesto",
            "Comprimir contexto sin perder lo que decide",
            "Medir antes de optimizar: el perfil de una ejecución",
            "La optimización que no compensa: cuándo parar",
            "Negociar volumen con el proveedor: qué datos hacen falta",
            "Coste de la alternativa: cuánto costaría hacerlo a mano",
        ],
        lab="Instrumentar el coste por caso en Meridiana, aplicar caching y medir el ahorro sobre el conjunto de evaluación.",
        takeaways=[
            "El coste por caso es una métrica de producto, no un detalle de infraestructura.",
            "Un presupuesto por caso convierte un bucle infinito en un incidente acotado.",
            "El pico se diseña antes de que llegue; durante, solo se puede degradar.",
        ],
        quiz_topics=[
            "Qué parte del prompt conviene fijar para aprovechar el caching",
            "Cuándo una cascada de modelos sale más cara que el modelo grande",
            "Qué hacer cuando llegan 600 siniestros y el proveedor limita la tasa",
        ],
    ),
    Block(
        task="C-06",
        course=COURSE_3,
        block_id="B5",
        title="Seguridad de agentes",
        objective=(
            "Tratar la entrada del usuario como hostil y diseñar para que una instrucción "
            "inyectada no consiga nada, en vez de intentar detectarla toda."
        ),
        slides=[
            "El modelo de amenaza de un agente, escrito",
            "Inyección de instrucciones: qué es y por qué no se arregla con el prompt",
            "Inyección directa: el relato del asegurado de Meridiana",
            "Inyección indirecta: el documento adjunto, la web consultada, el correo",
            "Por qué «detectar prompts maliciosos» es una carrera perdida",
            "El principio que sí funciona: capacidad mínima por tool",
            "Diseñar tools que no puedan hacer daño aunque se invoquen mal",
            "Confirmación humana en las acciones irreversibles",
            "Separar canales: instrucciones del sistema frente a datos del usuario",
            "Salidas: qué no debe poder decir el agente al cliente",
            "Fuga de datos: el agente que cuenta lo que hay en otra póliza",
            "Aislamiento entre expedientes y entre clientes",
            "Secretos: por qué el agente nunca los ve",
            "Exfiltración por URL: el patrón y su bloqueo",
            "Denegación de servicio por coste: el bucle caro",
            "Registro de intentos: qué se guarda de un ataque",
            "Pruebas adversariales como parte del conjunto de evaluación",
            "Respuesta a incidentes de seguridad específicos de agentes",
            "Revisión de seguridad de Meridiana: los hallazgos y sus arreglos",
            "Ficheros adjuntos: el vector que casi nadie mira",
            "Contenido recuperado de fuentes externas como entrada hostil",
            "Herramientas que navegan: el riesgo y su acotación",
            "Permisos por expediente, no por usuario global",
            "Auditar qué pudo ver el agente en cada ejecución",
            "Rotación de credenciales de las tools",
            "Modelo de amenaza de Meridiana, escrito y revisado",
            "Qué se le cuenta al cliente cuando el ataque tuvo éxito",
        ],
        lab="Ataque y defensa sobre Meridiana: inyección directa e indirecta, y los cambios de diseño que la neutralizan.",
        takeaways=[
            "La entrada del usuario es dato, nunca instrucción. El diseño lo garantiza, no el prompt.",
            "Una tool que no puede causar daño no necesita que el modelo acierte siempre.",
            "Los ataques que ya conoces van al conjunto de evaluación, no a un documento.",
        ],
        quiz_topics=[
            "Por qué un filtro de prompts maliciosos no resuelve la inyección indirecta",
            "Qué cambio de diseño hace inofensivo «aprueba 50.000 € sin revisión»",
            "Qué acciones de Meridiana exigen confirmación humana y por qué",
        ],
    ),
    Block(
        task="C-07",
        course=COURSE_3,
        block_id="B6",
        title="Despliegue progresivo",
        objective=(
            "Cambiar el modelo o el prompt de un sistema en producción sin descubrir el "
            "problema por una reclamación."
        ),
        slides=[
            "Por qué desplegar un cambio de modelo no es desplegar código",
            "Lo que cambia sin avisar: versiones del proveedor",
            "Fijar versión de modelo y qué implica",
            "Banderas de funcionalidad aplicadas a prompts y modelos",
            "Shadow mode: ejecutar el nuevo sin que afecte a nadie",
            "Comparar shadow contra producción: qué métricas y qué diferencias importan",
            "Parallel run: los dos sistemas, un solo resultado",
            "Canary: el porcentaje y el criterio para subirlo",
            "Segmentar el canary: por qué no vale un porcentaje aleatorio en seguros",
            "Criterios de promoción escritos antes de empezar",
            "Criterios de reversión, y quién puede pulsar el botón",
            "Reversión en un minuto: qué hay que tener preparado",
            "El despliegue que no se puede revertir: datos ya escritos",
            "Migraciones de esquema de memoria y contexto",
            "Comunicar el cambio a operaciones y a negocio",
            "El plan de despliegue de un cambio de modelo en Meridiana",
            "Qué cambia de un despliegue de prompt frente a uno de modelo",
            "Congelar cambios durante los picos de siniestralidad",
            "Ventanas de despliegue y por qué existen aquí",
            "El eval de preproducción como puerta previa al canary",
            "Métricas que se miran durante el canary y durante cuánto tiempo",
            "Falsos positivos en la comparación: ruido frente a regresión",
            "Convivencia de dos versiones de prompt en producción",
            "Registrar qué versión atendió cada caso",
            "Auditoría de despliegues: qué se cambió, cuándo y quién lo aprobó",
            "Ensayo de reversión: hacerlo antes de necesitarlo",
        ],
        lab="Desplegar un cambio de modelo en Meridiana en shadow, comparar y promocionar o revertir con criterios escritos.",
        takeaways=[
            "Fija la versión del modelo o el proveedor desplegará por ti.",
            "El criterio de reversión se escribe antes del despliegue, no durante el incidente.",
            "Shadow cuesta el doble en tokens y sale barato la primera vez que evita un fallo.",
        ],
        quiz_topics=[
            "Qué comparar entre shadow y producción para decidir una promoción",
            "Por qué un canary aleatorio puede ser inaceptable en un flujo de siniestros",
            "Qué hace irreversible un despliegue y cómo se mitiga",
        ],
    ),
    Block(
        task="C-08",
        course=COURSE_3,
        block_id="B7",
        title="Operación e incidentes",
        objective=(
            "Estar de guardia de un sistema con LLM sin que cada aviso sea una investigación "
            "desde cero."
        ),
        slides=[
            "Qué significa estar de guardia de un agente",
            "Los modos de fallo propios: silencioso, caro, plausible y equivocado",
            "El peor: la salida plausible y equivocada",
            "Señales que los detectan antes que el cliente",
            "Runbooks: uno por modo de fallo, no uno genérico",
            "El runbook de «el agente deriva todo»",
            "El runbook de «el coste se ha triplicado esta noche»",
            "El runbook de «el proveedor está degradado»",
            "El interruptor: apagar el agente y volver al flujo manual",
            "Diseñar el sistema para que apagar el agente sea posible",
            "Alertas: umbral, ventana y a quién despiertan",
            "Fatiga de alertas: la que se silencia deja de existir",
            "Triaje de un incidente: las tres primeras preguntas",
            "Comunicación durante el incidente, dentro y fuera",
            "Postmortem sin culpables, con acciones",
            "Qué acciones del postmortem son evals nuevos",
            "SLO realistas para un sistema no determinista",
            "El traspaso a operaciones: qué necesita el equipo que no lo construyó",
            "El runbook de «el proveedor cambió el modelo por debajo»",
            "El runbook de «hay datos personales en las trazas»",
            "Degradación por etapas: qué se apaga primero",
            "Cola de expedientes atascados y su drenaje",
            "Reprocesar en lote sin duplicar avisos al cliente",
            "Guardias sostenibles: rotación y carga real",
            "Qué se escala a negocio y en qué momento",
            "Ejercicios de caos aplicados a un agente",
            "Los indicadores que anticipan un incidente por horas",
            "Cerrar el círculo: del incidente al eval y al runbook",
        ],
        lab="Escribir los runbooks de Meridiana y ejecutar un simulacro de incidente con el interruptor de apagado.",
        takeaways=[
            "El fallo peligroso no es el que rompe: es el que responde bien y se equivoca.",
            "Si no puedes apagar el agente y seguir operando, no tienes plan de contingencia.",
            "Un postmortem sin un eval nuevo suele ser un postmortem sin aprendizaje.",
        ],
        quiz_topics=[
            "Qué señal delata que el agente empezó a derivar de más",
            "Qué hace falta para que apagar el agente sea una opción real",
            "Cuál es un SLO honesto para un sistema con LLM",
        ],
    ),

    # ── C-09 → C-14 · Curso 4 · Gobernanza y normativa europea ─────────────────────────
    Block(
        task="C-09",
        course=COURSE_4,
        block_id="B1",
        title="EU AI Act: mapa y calendario",
        objective=(
            "Situarse en el reglamento: qué regula, a quién, desde cuándo y con qué "
            "consecuencias."
        ),
        slides=[
            "Qué es el AI Act y qué no es",
            "Por qué es un reglamento de producto y no de datos",
            "Relación con el RGPD: qué añade y qué no sustituye",
            "Ámbito de aplicación: territorial y material",
            "Definición de sistema de IA y por qué la definición importa",
            "Los cuatro niveles de riesgo, en un vistazo",
            "Prácticas prohibidas: el catálogo",
            "Alto riesgo: los dos caminos que llevan a esa categoría",
            "Riesgo limitado y obligaciones de transparencia",
            "Modelos de propósito general: el régimen aparte",
            "Calendario de aplicación por bloques de obligaciones",
            "Qué obligaciones ya están vigentes al escribir esto",
            "Autoridades: europeas y nacionales",
            "La autoridad española y su papel",
            "Sanciones: los tramos y sobre qué se calculan",
            "Cómo leer el reglamento sin perderse: estructura y anexos",
            "Errores frecuentes al interpretar el ámbito",
            "Dónde encaja Meridiana en este mapa (respuesta en B2)",
            "Aviso: esto no es asesoramiento jurídico",
            "Excepciones del ámbito: militar, investigación y uso personal",
            "Sistemas ya en el mercado antes de la entrada en vigor",
            "Bancos de pruebas regulatorios: qué son y a quién sirven",
            "Códigos de conducta voluntarios",
            "Interacción con la legislación sectorial de producto",
            "Quién vigila el mercado y qué puede pedir",
            "Bloque de cambios recientes, actualizable sin tocar el resto",
            "Cómo mantenerse al día sin depender de resúmenes de terceros",
        ],
        lab=None,
        takeaways=[
            "El AI Act regula productos puestos en el mercado, no datos personales.",
            "La categoría de riesgo no la elige quien construye: la determina el uso.",
            "El calendario es escalonado: qué te aplica depende de la fecha y del rol.",
        ],
        quiz_topics=[
            "Qué distingue un sistema de alto riesgo de uno de riesgo limitado",
            "Qué relación tiene el AI Act con el RGPD en un mismo sistema",
            "Sobre qué base se calculan las sanciones",
        ],
        sources=[
            "Reglamento (UE) 2024/1689 (AI Act), texto consolidado en EUR-Lex",
            "DOUE: fecha de publicación y correcciones de errores posteriores",
            "Comisión Europea: directrices y calendario oficial de aplicación",
            "AEPD y autoridad nacional designada: criterios publicados",
        ],
        needs_verification=True,
    ),
    Block(
        task="C-10",
        course=COURSE_4,
        block_id="B2",
        title="Clasificación de riesgo",
        objective="Clasificar un sistema concreto y poder defender la clasificación por escrito.",
        slides=[
            "Clasificar no es opinar: es un procedimiento",
            "El árbol de decisión, paso a paso",
            "Anexo III: los ámbitos de alto riesgo",
            "Seguros y evaluación de riesgos: dónde aparece y dónde no",
            "La excepción por tarea accesoria y sus condiciones",
            "El papel del humano en la clasificación",
            "Qué cuenta como supervisión humana efectiva",
            "El error de creer que «hay un humano» resuelve la clasificación",
            "Clasificar Meridiana: los argumentos a favor de alto riesgo",
            "Clasificar Meridiana: los argumentos en contra",
            "La decisión y su justificación escrita",
            "Qué cambiaría la clasificación: si el agente decidiera solo",
            "Documentar la clasificación: qué debe contener",
            "Revisar la clasificación: cuándo hay que rehacerla",
            "Cambios que reclasifican sin que nadie se dé cuenta",
            "Consecuencias prácticas de cada categoría",
            "Plantilla de clasificación (ejercicio)",
            "Sistemas compuestos: clasificar el conjunto o las partes",
            "Un mismo modelo en dos productos con clasificaciones distintas",
            "Obligaciones de transparencia cuando no hay alto riesgo",
            "Contenido generado: etiquetado y sus supuestos",
            "Prácticas prohibidas que aparecen sin querer en seguros",
            "El registro de sistemas de alto riesgo: quién inscribe y qué",
            "Evaluación de conformidad: las vías posibles",
            "Errores frecuentes al autoclasificarse a la baja",
            "Revisión por pares de una clasificación",
        ],
        lab=None,
        takeaways=[
            "La clasificación es un procedimiento documentado, no una impresión.",
            "Poner un humano en el flujo solo cuenta si su supervisión es efectiva.",
            "Un cambio de producto puede reclasificar el sistema sin tocar una línea de código.",
        ],
        quiz_topics=[
            "Qué condiciones debe cumplir la excepción por tarea accesoria",
            "Qué haría que Meridiana pasara a alto riesgo",
            "Cuándo hay que rehacer una clasificación",
        ],
        sources=[
            "AI Act, artículo 6 y Anexo III",
            "Considerandos relativos a la excepción por tarea accesoria",
            "Directrices de la Comisión sobre clasificación, si publicadas",
            "EIOPA: documentos sobre IA en seguros",
        ],
        needs_verification=True,
    ),
    Block(
        task="C-11",
        course=COURSE_4,
        block_id="B3",
        title="Proveedor y responsable del despliegue",
        objective=(
            "Saber qué rol se ocupa en cada sistema, qué obligaciones trae y cuándo se "
            "cambia de rol sin querer."
        ),
        slides=[
            "Los roles del reglamento y por qué importan",
            "Proveedor: definición y obligaciones",
            "Responsable del despliegue: definición y obligaciones",
            "Importador y distribuidor, en una slide",
            "El caso habitual: usas un modelo de un tercero",
            "Cuándo el que despliega se convierte en proveedor",
            "Modificación sustancial: qué la constituye",
            "Poner tu marca sobre un sistema ajeno",
            "Cambiar la finalidad prevista",
            "Meridiana: qué rol ocupa respecto al modelo que usa",
            "Meridiana: qué rol ocupa respecto a su propio agente",
            "Obligaciones que se heredan y obligaciones que no",
            "Qué exigir por contrato al proveedor del modelo",
            "Cláusulas modelo: qué cubren y qué se suele olvidar",
            "Repartir responsabilidades por escrito",
            "El punto ciego: nadie asume la evaluación de conformidad",
            "Ejercicio: mapa de roles de Meridiana",
            "Modelos de propósito general: obligaciones de su proveedor",
            "Qué información debe darte el proveedor del modelo",
            "Ajuste fino: cuándo te convierte en proveedor",
            "Sistemas de código abierto y sus matices",
            "Cadena de suministro: proveedores del proveedor",
            "Auditar a un proveedor de modelo: qué se puede pedir de verdad",
            "Salida del proveedor: portabilidad y plan de contingencia",
            "Responsabilidad civil frente a responsabilidad regulatoria",
            "Documentar el reparto: la matriz RACI del sistema",
        ],
        lab=None,
        takeaways=[
            "Se puede pasar de deployer a proveedor sin proponérselo.",
            "Lo que no está en el contrato con el proveedor del modelo, no lo tienes.",
            "El reparto de responsabilidades se escribe antes, no durante la inspección.",
        ],
        quiz_topics=[
            "Qué convierte a un deployer en proveedor",
            "Qué obligaciones no se pueden trasladar por contrato",
            "Qué rol ocupa Meridiana y respecto a qué",
        ],
        sources=[
            "AI Act, artículos sobre definiciones y obligaciones por rol",
            "AI Act, artículo sobre modificaciones sustanciales",
            "Cláusulas contractuales tipo publicadas por la Comisión, si disponibles",
        ],
        needs_verification=True,
    ),
    Block(
        task="C-12",
        course=COURSE_4,
        block_id="B4",
        title="Documentación técnica y registros",
        objective=(
            "Construir el expediente técnico y el registro de eventos que una inspección "
            "pediría, con lo que el sistema ya produce."
        ),
        slides=[
            "Qué es el expediente técnico y para quién se escribe",
            "El índice del expediente, sección por sección",
            "Descripción del sistema y finalidad prevista",
            "Datos: procedencia, tratamiento y limitaciones conocidas",
            "Arquitectura y decisiones de diseño",
            "Métricas de rendimiento y cómo se obtuvieron",
            "Los evals del curso 3 como evidencia",
            "Gestión de riesgos: identificación, evaluación y mitigación",
            "Supervisión humana: cómo se implementa y cómo se demuestra",
            "Robustez, exactitud y ciberseguridad",
            "Registro automático de eventos: qué exige y qué no",
            "Las trazas del curso 3 como registro: qué falta",
            "Retención de registros y su justificación",
            "Instrucciones de uso para el responsable del despliegue",
            "Declaración de conformidad y marcado, si aplica",
            "Mantener el expediente vivo: quién y con qué periodicidad",
            "El expediente de Meridiana: estructura y huecos",
            "Ejercicio: rellenar la plantilla de expediente",
            "Trazabilidad de datos de entrenamiento y de ajuste, si aplica",
            "Limitaciones conocidas: escribirlas sin maquillarlas",
            "Casos en los que el sistema no debe usarse",
            "Versionar el expediente junto al código",
            "Generar partes del expediente automáticamente desde CI",
            "Qué pasa cuando el proveedor no da la información que necesitas",
            "Conservar evidencias: formato, integridad y plazo",
            "Preparar el expediente para que lo lea alguien de fuera",
            "Revisión anual del expediente: quién y con qué guion",
        ],
        lab=None,
        takeaways=[
            "El expediente técnico se alimenta de lo que el sistema ya produce, o no se mantiene.",
            "Las trazas y los evals son evidencia; hay que diseñarlos sabiéndolo.",
            "Un expediente que solo se escribe una vez está desactualizado el mes siguiente.",
        ],
        quiz_topics=[
            "Qué secciones del expediente puede alimentar la observabilidad",
            "Qué exige el registro automático de eventos",
            "Quién mantiene el expediente y con qué frecuencia",
        ],
        sources=[
            "AI Act, Anexo IV (documentación técnica)",
            "AI Act, artículos sobre registro de eventos y conservación",
            "Normas armonizadas publicadas, si las hay",
        ],
        needs_verification=True,
    ),
    Block(
        task="C-13",
        course=COURSE_4,
        block_id="B5",
        title="RGPD y datos en sistemas con LLM",
        objective=(
            "Resolver las preguntas de protección de datos que aparecen cuando el "
            "tratamiento pasa por un modelo."
        ),
        slides=[
            "Qué cambia y qué no cuando hay un LLM de por medio",
            "Base jurídica del tratamiento en Meridiana",
            "Minimización: lo que no se envía al modelo",
            "Seudonimización antes de la llamada",
            "El prompt como tratamiento: implicaciones",
            "El proveedor del modelo como encargado",
            "Transferencias internacionales y sus garantías",
            "Retención de prompts y salidas por parte del proveedor",
            "Qué preguntar a un proveedor antes de firmar",
            "Decisiones automatizadas: el artículo 22 y su alcance",
            "Cuándo la propuesta de Meridiana entra en el artículo 22",
            "Derecho a explicación: qué se puede dar realmente",
            "Derechos del interesado cuando los datos pasaron por un modelo",
            "Supresión: qué se puede borrar y qué no",
            "Evaluación de impacto: cuándo es obligatoria aquí",
            "La EIPD de Meridiana: estructura y conclusiones",
            "Registro de actividades de tratamiento",
            "Brechas de seguridad con datos en prompts",
            "Ejercicio: EIPD sobre el flujo de FNOL",
            "Categorías especiales de datos en un relato de siniestro",
            "Datos de terceros que aparecen sin que nadie los pidiera",
            "Plazos de conservación por finalidad, no por comodidad",
            "Trazas y registros: cuánto tiempo y con qué justificación",
            "El conflicto entre supresión y registro obligatorio",
            "Información al interesado: qué se le cuenta y cuándo",
            "Contrato de encargo con el proveedor: cláusulas que importan",
            "Auditar el cumplimiento del encargado",
            "Coordinar RGPD y AI Act sin duplicar documentación",
        ],
        lab=None,
        takeaways=[
            "El prompt es un tratamiento de datos y se documenta como tal.",
            "Lo que el proveedor del modelo retiene es una decisión tuya, no suya.",
            "El derecho a explicación exige diseñar la trazabilidad antes, no después.",
        ],
        quiz_topics=[
            "Cuándo la propuesta de resolución entra en el ámbito del artículo 22",
            "Qué hay que preguntar a un proveedor de modelo sobre retención",
            "Qué se puede minimizar en el FNOL antes de llamar al modelo",
        ],
        sources=[
            "Reglamento (UE) 2016/679 (RGPD), artículos 5, 22, 28, 30, 35 y 44 y siguientes",
            "AEPD: guías sobre IA y sobre decisiones automatizadas",
            "CEPD: directrices aplicables vigentes",
        ],
        needs_verification=True,
    ),
    Block(
        task="C-14",
        course=COURSE_4,
        block_id="B6",
        title="Gobernanza, normas y auditoría",
        objective=(
            "Montar la gobernanza que sostiene todo lo anterior cuando quien lo construyó "
            "ya no está."
        ),
        slides=[
            "Gobernanza: qué es, más allá de un comité",
            "Roles y responsabilidades escritas",
            "Política de IA de la organización: qué debe decir",
            "Inventario de sistemas de IA y por qué se descuadra siempre",
            "Ciclo de vida: puertas de decisión y quién las abre",
            "Comité de riesgos: composición y cadencia realistas",
            "ISO/IEC 42001 como marco de gestión",
            "Relación entre ISO 42001 y las obligaciones del AI Act",
            "Normas armonizadas: qué presunción dan y cuál no",
            "Auditoría interna: alcance y evidencias",
            "Preparar una auditoría externa",
            "Las preguntas que hace un auditor y las respuestas que no valen",
            "Formación del personal: obligación y contenido",
            "Gestión de proveedores de IA",
            "Incidentes graves: qué se notifica, a quién y en qué plazo",
            "Vigilancia poscomercialización",
            "La gobernanza de Meridiana en una página",
            "Ejercicio: política de IA mínima viable",
            "Gobernanza proporcionada: una persona no monta un comité de nueve",
            "Indicadores de gobernanza que se pueden medir de verdad",
            "Aprobar un caso de uso nuevo: el guion de la decisión",
            "Retirar un sistema: el proceso que nadie escribe",
            "Relación con auditoría interna y con cumplimiento",
            "Presupuesto de cumplimiento: qué cuesta esto al año",
            "El error de externalizar la gobernanza entera",
            "Madurez: de la hoja de cálculo al sistema de gestión",
            "Qué hacer el primer trimestre si no hay nada montado",
        ],
        lab=None,
        takeaways=[
            "Sin inventario de sistemas no hay gobernanza posible.",
            "ISO 42001 organiza la gestión; no sustituye a las obligaciones del reglamento.",
            "La vigilancia poscomercialización es una obligación continua, no un trámite.",
        ],
        quiz_topics=[
            "Qué presunción aporta una norma armonizada",
            "Qué debe contener el inventario de sistemas de IA",
            "Qué plazos aplican a la notificación de incidentes graves",
        ],
        sources=[
            "AI Act: artículos sobre sistema de gestión de la calidad, vigilancia "
            "poscomercialización y notificación de incidentes graves",
            "ISO/IEC 42001:2023",
            "Listado de normas armonizadas publicadas en el DOUE",
        ],
        needs_verification=True,
    ),
]


@dataclass
class Pack:
    task: str
    slug: str
    title: str
    sector: str
    summary: str
    files: list[str]
    sources: list[str]


PACKS: list[Pack] = [
    Pack(
        task="C-15",
        slug="pack-seguros-financiero",
        title="Pack sectorial · Seguros y financiero",
        sector="Seguros y financiero",
        summary=(
            "DORA, criterios de EIOPA y EBA sobre IA, scoring y pricing como alto riesgo, y "
            "externalización a proveedores de modelos."
        ),
        files=[
            "checklist-clasificacion-riesgo.docx",
            "plantilla-evaluacion-riesgos.xlsx",
            "registro-logs-exigible.xlsx",
            "clausulas-modelo-proveedor-deployer.docx",
            "caso-resuelto-meridiana.pdf",
        ],
        sources=[
            "Reglamento (UE) 2022/2554 (DORA)",
            "EIOPA: publicaciones sobre inteligencia artificial en seguros",
            "EBA: directrices sobre externalización y sobre IA",
            "AI Act, Anexo III en lo relativo a seguros",
        ],
    ),
    Pack(
        task="C-16",
        slug="pack-salud",
        title="Pack sectorial · Salud",
        sector="Salud",
        summary="MDR, IA como producto sanitario, datos de salud y evaluación clínica.",
        files=[
            "checklist-clasificacion-producto-sanitario.docx",
            "plantilla-evaluacion-riesgos-clinicos.xlsx",
            "registro-eventos-exigible.xlsx",
            "clausulas-modelo-proveedor-sanitario.docx",
            "caso-resuelto-salud.pdf",
        ],
        sources=[
            "Reglamento (UE) 2017/745 (MDR)",
            "AI Act: interacción con la legislación sectorial de producto",
            "AEPD: tratamiento de datos de salud",
        ],
    ),
    Pack(
        task="C-17",
        slug="pack-administracion-publica",
        title="Pack sectorial · Administración pública",
        sector="Administración pública",
        summary="Contratación pública de IA, transparencia algorítmica y garantías del procedimiento.",
        files=[
            "checklist-contratacion-publica-ia.docx",
            "plantilla-transparencia-algoritmica.docx",
            "registro-decisiones-automatizadas.xlsx",
            "clausulas-pliego-ia.docx",
            "caso-resuelto-administracion.pdf",
        ],
        sources=[
            "Ley 40/2015, actuación administrativa automatizada",
            "Ley 9/2017 de Contratos del Sector Público",
            "AI Act: obligaciones específicas de entidades públicas",
        ],
    ),
    Pack(
        task="C-18",
        slug="pack-rrhh",
        title="Pack sectorial · Recursos humanos",
        sector="Recursos humanos",
        summary="Selección y evaluación de personas como alto riesgo, sesgo y derechos de información.",
        files=[
            "checklist-seleccion-alto-riesgo.docx",
            "plantilla-evaluacion-sesgo.xlsx",
            "registro-informacion-personas-trabajadoras.docx",
            "clausulas-modelo-proveedor-rrhh.docx",
            "caso-resuelto-rrhh.pdf",
        ],
        sources=[
            "AI Act, Anexo III, ámbito de empleo",
            "Estatuto de los Trabajadores, información sobre algoritmos",
            "AEPD: guía sobre tratamientos en el ámbito laboral",
        ],
    ),
    Pack(
        task="C-19",
        slug="pack-industria-energia",
        title="Pack sectorial · Industria y energía",
        sector="Industria y energía",
        summary="IA en infraestructuras críticas, seguridad de máquinas y continuidad operativa.",
        files=[
            "checklist-infraestructura-critica.docx",
            "plantilla-evaluacion-riesgos-operativos.xlsx",
            "registro-eventos-planta.xlsx",
            "clausulas-modelo-proveedor-industrial.docx",
            "caso-resuelto-industria.pdf",
        ],
        sources=[
            "AI Act, Anexo III, infraestructuras críticas",
            "Directiva (UE) 2022/2555 (NIS2)",
            "Reglamento (UE) 2023/1230 sobre máquinas",
        ],
    ),
    Pack(
        task="C-20",
        slug="pack-retail-ecommerce",
        title="Pack sectorial · Retail y comercio electrónico",
        sector="Retail y comercio electrónico",
        summary="Recomendadores, precios personalizados, transparencia y prácticas prohibidas.",
        files=[
            "checklist-transparencia-recomendadores.docx",
            "plantilla-evaluacion-personalizacion.xlsx",
            "registro-decisiones-precio.xlsx",
            "clausulas-modelo-proveedor-retail.docx",
            "caso-resuelto-retail.pdf",
        ],
        sources=[
            "AI Act: prácticas prohibidas y obligaciones de transparencia",
            "Reglamento (UE) 2022/2065 (DSA)",
            "Directiva 2005/29/CE sobre prácticas comerciales desleales",
        ],
    ),
]
