using Inkoova.Academy.Domain.Common;
using Inkoova.Academy.Domain.ValueObjects;

namespace Inkoova.Academy.Domain.Affiliates;

public enum PayoutStatus
{
    /// <summary>Generated by the monthly job, waiting for the affiliate's invoice.</summary>
    AwaitingInvoice,

    /// <summary>Invoice received (or self-billed). Ready to transfer.</summary>
    ReadyToPay,

    Paid,
    Cancelled
}

/// <summary>
/// Monthly settlement for one affiliate. Deterministic by construction: the period and the
/// set of commissions fully determine the total, so regenerating produces the same PDF
/// (T-16 acceptance criteria).
/// </summary>
public sealed class Payout
{
    /// <summary>Below this the balance carries over to the next month (T-16).</summary>
    public static readonly Money MinimumPayout = Money.Euros(5_000);

    public Guid Id { get; private set; }
    public Guid AffiliateId { get; private set; }

    /// <summary>Settlement period, first day inclusive.</summary>
    public DateOnly PeriodStart { get; private set; }

    /// <summary>Settlement period, last day inclusive.</summary>
    public DateOnly PeriodEnd { get; private set; }

    public Money Total { get; private set; }

    /// <summary>Balance below the minimum that was carried into this settlement.</summary>
    public Money CarriedOverIn { get; private set; }

    public PayoutStatus Status { get; private set; }
    public string? InvoiceRef { get; private set; }
    public string? StatementContentRef { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset? PaidAt { get; private set; }

    private Payout(
        Guid id,
        Guid affiliateId,
        DateOnly periodStart,
        DateOnly periodEnd,
        Money total,
        Money carriedOverIn,
        PayoutStatus status,
        string? invoiceRef,
        string? statementContentRef,
        DateTimeOffset createdAt,
        DateTimeOffset? paidAt)
    {
        Id = id;
        AffiliateId = affiliateId;
        PeriodStart = periodStart;
        PeriodEnd = periodEnd;
        Total = total;
        CarriedOverIn = carriedOverIn;
        Status = status;
        InvoiceRef = invoiceRef;
        StatementContentRef = statementContentRef;
        CreatedAt = createdAt;
        PaidAt = paidAt;
    }

    public static Result<Payout, Error> Settle(
        Guid id,
        Affiliate affiliate,
        DateOnly periodStart,
        DateOnly periodEnd,
        IReadOnlyList<Commission> commissions,
        Money carriedOverIn,
        DateTimeOffset now)
    {
        if (periodEnd < periodStart)
        {
            return Error.Validation("payout.invalid_period", "El periodo de liquidación es inválido.");
        }

        if (!affiliate.CanBePaid)
        {
            return Error.Conflict(
                "payout.affiliate_not_payable",
                "El afiliado no tiene los datos fiscales completos para liquidar.");
        }

        var notPayable = commissions.Where(c => !c.IsPayable).ToArray();
        if (notPayable.Length > 0)
        {
            return Error.Conflict(
                "payout.commission_not_payable",
                "La liquidación incluye comisiones que no están aprobadas o ya están pagadas.");
        }

        if (commissions.Any(c => c.AffiliateId != affiliate.Id))
        {
            return Error.Validation("payout.commission_other_affiliate", "Hay comisiones de otro afiliado.");
        }

        var total = carriedOverIn;
        foreach (var commission in commissions.OrderBy(c => c.CreatedAt).ThenBy(c => c.Id))
        {
            var sum = total.Add(commission.Amount);
            if (sum.IsFailure)
            {
                return sum.Error;
            }

            total = sum.Value;
        }

        return new Payout(
            id, affiliate.Id, periodStart, periodEnd, total, carriedOverIn,
            PayoutStatus.AwaitingInvoice, invoiceRef: null, statementContentRef: null, now, paidAt: null);
    }

    public static Payout Rehydrate(
        Guid id,
        Guid affiliateId,
        DateOnly periodStart,
        DateOnly periodEnd,
        Money total,
        Money carriedOverIn,
        PayoutStatus status,
        string? invoiceRef,
        string? statementContentRef,
        DateTimeOffset createdAt,
        DateTimeOffset? paidAt) =>
        new(id, affiliateId, periodStart, periodEnd, total, carriedOverIn, status,
            invoiceRef, statementContentRef, createdAt, paidAt);

    /// <summary>Below the minimum the money is not transferred; the balance rolls forward.</summary>
    public bool ReachesMinimum => Total.AmountInCents >= MinimumPayout.AmountInCents;

    public void AttachStatement(string contentRef) => StatementContentRef = contentRef;

    public Result<Unit, Error> RegisterInvoice(string invoiceRef)
    {
        if (string.IsNullOrWhiteSpace(invoiceRef))
        {
            return Error.Validation("payout.invoice_empty", "La referencia de factura no puede estar vacía.");
        }

        if (Status != PayoutStatus.AwaitingInvoice)
        {
            return Error.Conflict("payout.not_awaiting_invoice", "La liquidación no está esperando factura.");
        }

        InvoiceRef = invoiceRef.Trim();
        Status = PayoutStatus.ReadyToPay;
        return Unit.Value;
    }

    public Result<Unit, Error> MarkPaid(DateTimeOffset now)
    {
        if (Status != PayoutStatus.ReadyToPay)
        {
            return Error.Conflict("payout.not_ready", "Solo se puede pagar una liquidación con factura registrada.");
        }

        if (!ReachesMinimum)
        {
            return Error.Conflict(
                "payout.below_minimum",
                $"El total no alcanza el mínimo de {MinimumPayout}.");
        }

        Status = PayoutStatus.Paid;
        PaidAt = now;
        return Unit.Value;
    }

    public void Cancel() => Status = PayoutStatus.Cancelled;
}
